[colors.primary]
foreground = "#D3C6AA"
background = "#272E33" 

[colors.normal]
red = "#E67E80"
green = "#A7C080"
yellow = "#DBBC7F"
blue = "#7FBBB3"
magenta = "#D699B6"
cyan = "#83C092"
white = "#D3C6AA"

[colors.dim]
black = "#1E2326"
red = "#493B40"
green = "#3C4841"
yellow = "#45443C"
blue = "#384B55"
magenta = "#463F48"

[window]
opacity = 0.8
padding = {x = 40, y = 40}
dynamic_padding = true
blur = true
decorations = "None"

[font]
normal = {family = "UbuntuMono Nerd Font",style = "Regular"}
size = 16

