local quotes = {
    "Believe in yourself.",
    "Dream big, start small.",
    "Push past your limits.",
    "Stay hungry, stay focused.",
    "Hard work beats talent.",
    "Keep moving forward.",
    "Success starts with courage.",
    "Make today count.",
    "Small steps, big impact.",
    "Turn setbacks into comebacks.",
    "Stay positive, work hard.",
    "Every day is a new chance.",
    "Your potential is limitless.",
    "Consistency creates success.",
    "Don’t stop until you’re proud.",
    "Great things take time.",
    "You are stronger than you think.",
    "Focus on progress, not perfection.",
    "Discipline equals freedom.",
    "Rise and grind.",
    "Never settle for less.",
    "Keep chasing your goals.",
    "Believe, achieve, succeed.",
    "Work hard in silence.",
    "Dream it, do it.",
    "Stay consistent, stay patient.",
    "The best time is now.",
    "Don’t wish for it, work for it.",
    "Action creates results.",
    "Fall down seven times, stand up eight.",
    "Nothing changes if nothing changes.",
    "Create your own luck.",
    "You only fail if you quit.",
    "Stay disciplined, stay unstoppable.",
    "Effort builds greatness.",
    "Your future is created today.",
    "Progress, not excuses.",
    "Stay focused and never quit.",
    "Do more, complain less.",
    "Push harder than yesterday.",
    "Be your own motivation.",
    "Keep the vision, trust the process.",
    "One step at a time.",
    "Your hustle defines you.",
    "Failure is just feedback.",
    "You control your destiny.",
    "Sacrifice now, shine later.",
    "Greatness requires sacrifice.",
    "Never give up, never give in.",
    "Your only limit is you.",
}

return quotes
